export const designs = [
  {
    _id: "673f419049ed71755c8744a4",
    name: "Lucky unicorn - Good luck ecard",
    caption: "Good Luck I believe in you",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "cute",
      "funny",
      "animals",
      "unicorn",
      "mythical",
      "leaving",
      "cloud",
      "luck",
      "good-luck",
    ],
    createdAt: "2024-11-21T14:20:00.639Z",
    updatedAt: "2024-11-21T14:20:18.820Z",
    active: true,
  },
  {
    _id: "673f3fc149ed71755c8733c0",
    name: "Crossed out - personalised group Leaving Card",
    caption: "Sorry your Leaving (crossed out) Abandoning us",
    categories: ["leaving"],
    groupOnly: false,
    customisable: true,
    tags: [
      "group",
      "for her",
      "for boss / manager",
      "for colleague",
      "funny",
      "typography/words",
      "leaving",
      "pink",
      "sarcastic",
      "personalised",
    ],
    createdAt: "2024-11-21T14:12:17.573Z",
    updatedAt: "2024-11-21T14:13:52.122Z",
    active: true,
  },
  {
    _id: "673ef149162476969edad62b",
    name: "Pretty Balloon  - group leaving ecard",
    caption: "Up up and away. Goodbye and Good Luck",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "animated",
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "illustration",
      "hobby",
      "modern",
      "leaving",
      "balloon",
      "clouds",
    ],
    createdAt: "2024-11-21T08:37:29.353Z",
    updatedAt: "2024-11-21T08:47:55.838Z",
    format: "gif",
    active: true,
  },
  {
    _id: "673eeb11bad0992816112091",
    name: "Peony Bouquet - group leaving ecard",
    caption: "We've loved working with you",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for her",
      "for boss / manager",
      "for colleague",
      "modern",
      "flowers",
      "calligraphy",
      "peonies",
      "peony",
      "pink",
      "leaving",
    ],
    createdAt: "2024-11-21T08:10:57.228Z",
    updatedAt: "2024-11-21T08:11:29.438Z",
    active: true,
  },
  {
    _id: "673e88d69f0aff395e53e7c9",
    name: "Floral  - group leaving card",
    caption: "Sorry you're leaving",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for her",
      "individual",
      "modern",
      "illustration",
      "flowers",
      "leaving",
    ],
    createdAt: "2024-11-21T01:11:50.206Z",
    updatedAt: "2024-11-21T01:12:18.682Z",
    active: true,
  },
  {
    _id: "673e8871bad099281610c583",
    name: "archive box  - group leaving card",
    caption: "A fab new job. Bets of luck",
    categories: ["leaving", "congratulations"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "illustration",
      "work",
      "box",
      "leaving",
      "congratulations",
      "office",
    ],
    createdAt: "2024-11-21T01:10:09.186Z",
    updatedAt: "2024-11-21T01:10:40.343Z",
    active: true,
  },
  {
    _id: "673e85d2bad099281610c2a4",
    name: "Flower girl - group leaving ecard",
    caption: "good luck on your next adventure",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for her",
      "for colleague",
      "for boss / manager",
      "individual",
      "modern",
      "cute",
      "flowers",
      "typography/words",
      "calligraphy",
      "woman",
      "bag",
      "leaving",
    ],
    createdAt: "2024-11-21T00:58:58.510Z",
    updatedAt: "2024-11-21T00:59:20.212Z",
    active: true,
  },
  {
    _id: "673e856fbad099281610c23e",
    name: "Cheers - group leaving ecard",
    caption: "Here's to your next chapter",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "food and drink",
      "modern",
      "illustration",
      "hearts",
      "woman",
      "wine",
      "glasses",
      "cheers",
      "leaving",
    ],
    createdAt: "2024-11-21T00:57:19.823Z",
    updatedAt: "2024-11-21T00:57:46.008Z",
    active: true,
  },
  {
    _id: "673603905c9ed9b8bbbdcdfa",
    name: "Peony border - personalised message card",
    caption: "blank",
    categories: [
      "anniversary",
      "birthday",
      "leaving",
      "retirement",
      "get-well",
    ],
    groupOnly: false,
    customisable: true,
    tags: [
      "group",
      "personalised",
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "traditional",
      "photographic",
      "flowers",
      "peonies",
      "floral",
      "border",
      "birthday",
      "anniversary",
      "get-well",
      "leaving",
    ],
    createdAt: "2024-11-14T14:05:04.622Z",
    updatedAt: "2024-11-14T14:07:41.589Z",
    active: true,
  },
  {
    _id: "6735169ae8c991dba26b0d1f",
    name: "Chunky words - group leaving ecard",
    caption: "Goodbye and good luck",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for him",
      "for boss / manager",
      "for colleague",
      "individual",
      "typography/words",
      "bright",
      "bold",
      "leaving",
    ],
    createdAt: "2024-11-13T21:14:02.778Z",
    updatedAt: "2024-11-13T21:14:29.607Z",
    active: true,
  },
  {
    _id: "67351427e8c991dba26b07af",
    name: "Script and dots - group leaving ecard",
    caption: "Wishing you all the best",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "calligraphy",
      "for her",
      "for boss / manager",
      "for colleague",
      "individual",
      "modern",
      "typography/words",
      "pink",
      "paper",
      "leaving",
    ],
    createdAt: "2024-11-13T21:03:35.827Z",
    updatedAt: "2024-11-13T21:04:06.282Z",
    active: true,
  },
  {
    _id: "6734e8465c9ed9b8bbb9f36a",
    name: "Sky Sports News - group congratulations new job ecard",
    caption: "Congratulations on your new job. Work News.",
    categories: ["congratulations", "leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for him",
      "for boss / manager",
      "for colleague",
      "modern",
      "funny",
      "food and drink",
      "hobby",
      "congratulations",
      "leaving",
      "skysports",
      "football",
      "breaking",
      "news",
      "new-job",
      "briefcase",
    ],
    createdAt: "2024-11-13T17:56:22.461Z",
    updatedAt: "2024-11-13T17:56:39.103Z",
    active: true,
  },
  {
    _id: "6734e7415c9ed9b8bbb9eee0",
    name: "VAR - group congratulations and leaving ecard",
    caption:
      "VAR Checking possible transfer...Confirmed: New Job. Congratulations!",
    categories: ["leaving", "congratulations"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for him",
      "for boss / manager",
      "for colleague",
      "individual",
      "funny",
      "sports",
      "hobby",
      "typography/words",
      "football",
      "var",
      "referee",
      "congratulations",
      "great-job",
      "leaving",
    ],
    createdAt: "2024-11-13T17:52:01.016Z",
    updatedAt: "2024-11-13T17:57:04.298Z",
    active: true,
  },
  {
    _id: "66d0863c2dd7cf20d25773d2",
    name: "Matisse style - group leaving ecard",
    caption: "We will miss you!",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for boss / manager",
      "for colleague",
      "for her",
      "casual",
      "art",
      "impressionist",
      "matisse",
      "leaving",
      "bold",
    ],
    createdAt: "2024-08-29T14:31:24.782Z",
    updatedAt: "2024-08-29T14:32:05.505Z",
    active: true,
  },
  {
    _id: "66d071e8bede74f2e0634ce9",
    name: "Bold type flashing heart animated Miss you card",
    caption: "Miss You Miss You",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "animated",
      "casual",
      "for boss / manager",
      "for colleague",
      "individual",
      "miss",
      "you",
      "leaving",
      "hearts",
      "typography/words",
      "for her",
    ],
    createdAt: "2024-08-29T13:04:40.983Z",
    updatedAt: "2024-11-12T18:13:00.778Z",
    format: "gif",
    active: true,
  },
  {
    _id: "66c74a6a714e579a9fa51e92",
    name: "Sad bacon group leaving card",
    caption: "Your bacon our hearts. Please don't leave",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for boss / manager",
      "for colleague",
      "funny",
      "food and drink",
      "bacon",
      "sad",
      "leaving",
      "for him",
    ],
    createdAt: "2024-08-22T14:25:46.543Z",
    updatedAt: "2024-11-12T18:39:38.403Z",
    active: true,
  },
  {
    _id: "66c68555714e579a9fa14299",
    name: "Good Luck group leaving card",
    caption: "Good karma, karma, karma, karma, karma chameleon",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for boss / manager",
      "for colleague",
      "individual",
      "funny",
      "animals",
      "chameleon",
      "karma",
      "leaving",
      "luck",
      "cute",
    ],
    createdAt: "2024-08-22T00:24:53.901Z",
    updatedAt: "2024-11-13T11:19:20.295Z",
    active: true,
  },
  {
    _id: "66c6835c714e579a9fa1416f",
    name: "Big fish group congratulations card",
    caption: "Landed the big one. Congratulations on your new job",
    categories: ["congratulations", "leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for colleague",
      "for boss / manager",
      "individual",
      "funny",
      "hobby",
      "for him",
      "fish",
      "fishing",
      "leaving",
      "congratulations",
      "new-job",
      "pun",
      "sports",
    ],
    createdAt: "2024-08-22T00:16:28.439Z",
    updatedAt: "2024-11-13T10:53:57.426Z",
    active: true,
  },
  {
    _id: "66c67fdd748ba527204dce76",
    name: "Group leaving card for lawyer",
    caption:
      "We've reached a verdict, you're guilty of leaving us. Court of appeal (please don't leave)",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "for boss / manager",
      "for colleague",
      "funny",
      "lawyer",
      "jury",
      "court",
      "leaving",
      "verdict",
      "for him",
      "job",
    ],
    createdAt: "2024-08-22T00:01:33.983Z",
    updatedAt: "2024-11-13T11:55:19.898Z",
    active: true,
  },
  {
    _id: "66c67d96714e579a9fa13c7a",
    name: "Group leaving card for engineer",
    caption:
      "You're leaving, who's going to turn our computers on and off again",
    categories: ["leaving"],
    groupOnly: false,
    customisable: false,
    tags: [
      "group",
      "funny",
      "for boss / manager",
      "for colleague",
      "engineer",
      "reboot",
      "leaving",
      "computer",
      "rude",
      "for him",
      "job",
    ],
    createdAt: "2024-08-21T23:51:50.694Z",
    updatedAt: "2024-11-13T11:55:19.898Z",
    active: true,
  },
];
